
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,31,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,32,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,33,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,34,1);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,35,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,36,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,37,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,38,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,39,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,40,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,41,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,42,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,43,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,44,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,45,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,46,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,47,1);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,48,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,49,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,50,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,51,1);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,52,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,53,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,54,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,55,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,56,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,57,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,58,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,59,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (4,60,5);




insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,31,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,32,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,33,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,34,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,35,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,36,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,37,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,38,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,39,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,40,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,41,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,42,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,43,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,44,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,45,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,46,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,47,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,48,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,49,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,50,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,51,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,52,1);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,53,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,54,1);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,55,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,56,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,57,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,58,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,59,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (5,60,2);



insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,31,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,32,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,33,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,34,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,35,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,36,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,37,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,38,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,39,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,40,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,41,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,42,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,43,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,44,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,45,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,46,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,47,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,48,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,49,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,50,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,51,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,52,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,53,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,54,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,55,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,56,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,57,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,58,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,59,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (6,60,3);


insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,61,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,62,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,63,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,64,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,65,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,66,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,67,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,68,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,69,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,70,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,71,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,72,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,73,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,74,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,75,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,76,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,77,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,78,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,79,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,80,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,81,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,82,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (7,83,5);



insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,61,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,62,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,63,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,64,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,65,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,66,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,67,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,68,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,69,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,70,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,71,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,72,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,73,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,74,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,75,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,76,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,77,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,78,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,79,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,80,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,81,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,82,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (8,83,5);



insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,61,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,62,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,63,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,64,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,65,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,66,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,67,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,68,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,69,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,70,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,71,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,72,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,73,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,74,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,75,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,76,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,77,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,78,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,79,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,80,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,81,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,82,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (9,83,5);

insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,84,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,85,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,86,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,87,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,88,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,89,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,90,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,91,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,92,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,93,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,94,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,95,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,96,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,97,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,98,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,99,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,100,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,101,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,102,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,103,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,104,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,105,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,106,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,107,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,108,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,109,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,110,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,111,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,112,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (10,113,3);

insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,84,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,85,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,86,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,87,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,88,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,89,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,90,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,91,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,92,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,93,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,94,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,95,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,96,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,97,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,98,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,99,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,100,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,101,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,102,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,103,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,104,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,105,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,106,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,107,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,108,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,109,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,110,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,111,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,112,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (11,113,3);


insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,84,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,85,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,86,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,87,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,88,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,89,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,90,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,91,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,92,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,93,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,94,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,95,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,96,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,97,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,98,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,99,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,100,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,101,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,102,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,103,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,104,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,105,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,106,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,107,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,108,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,109,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,110,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,111,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,112,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (12,113,3);




insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,114,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,115,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,116,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,117,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,118,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,119,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,120,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,121,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,122,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,123,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,124,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,125,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,126,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,127,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,128,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,129,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,130,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,131,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,132,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,133,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,134,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,135,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,136,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,137,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,138,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,139,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,140,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,141,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,142,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (13,143,3);

insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,114,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,115,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,116,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,117,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,118,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,119,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,120,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,121,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,122,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,123,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,124,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,125,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,126,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,127,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,128,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,129,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,130,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,131,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,132,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,133,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,134,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,135,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,136,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,137,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,138,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,139,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,140,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,141,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,142,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (14,143,3);


insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,114,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,115,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,116,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,117,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,118,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,119,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,120,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,121,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,122,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,123,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,124,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,125,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,126,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,127,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,128,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,129,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,130,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,131,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,132,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,133,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,134,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,135,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,136,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,137,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,138,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,139,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,140,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,141,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,142,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (15,143,4);




insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,144,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,145,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,146,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,147,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,148,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,149,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,150,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,151,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,152,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,153,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,154,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,155,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,156,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,157,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,158,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,159,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,160,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,161,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,162,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,163,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,164,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,165,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,166,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,167,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,168,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,169,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,170,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,171,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,172,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (16,173,4);


insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,144,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,145,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,146,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,147,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,148,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,149,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,150,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,151,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,152,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,153,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,154,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,155,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,156,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,157,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,158,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,159,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,160,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,161,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,162,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,163,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,164,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,165,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,166,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,167,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,168,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,169,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,170,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,171,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,172,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (17,173,4);


insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,144,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,145,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,146,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,147,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,148,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,149,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,150,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,151,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,152,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,153,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,154,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,155,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,156,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,157,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,158,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,159,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,160,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,161,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,162,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,163,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,164,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,165,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,166,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,167,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,168,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,169,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,170,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,171,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,172,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (18,173,4);




insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,174,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,175,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,176,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,177,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,178,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,179,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,180,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,181,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,182,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,183,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,184,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,185,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,186,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,187,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,188,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,189,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,190,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,191,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,192,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,193,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,194,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,195,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,196,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,197,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,198,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,199,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,200,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,201,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,202,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (19,203,4);


insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,174,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,175,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,176,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,177,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,178,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,179,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,180,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,181,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,182,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,183,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,184,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,185,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,186,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,187,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,188,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,189,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,190,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,191,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,192,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,193,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,194,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,195,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,196,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,197,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,198,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,199,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,200,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,201,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,202,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (20,203,4);


insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,174,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,175,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,176,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,177,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,178,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,179,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,180,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,181,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,182,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,183,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,184,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,185,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,186,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,187,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,188,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,189,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,190,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,191,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,192,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,193,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,194,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,195,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,196,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,197,2);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,198,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,199,5);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,200,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,201,4);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,202,3);
insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION, ID_QUESTION_EVALUATION, POSITIONNEMENT)
values (21,203,4)